import type { ComplianceRule } from './rule-engine';

export const APP_STORE_RULES: ComplianceRule[] = [
  {
    id: 'app_store_5_1_1_iap',
    store: 'app_store',
    category: 'Commerce',
    title: 'In-App Purchase Required',
    description:
      'Apps offering digital goods or services must use Apple In-App Purchase. Alternative payment mechanisms are not permitted.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 5.1.1',
    keywords: ['payment', 'purchase', 'checkout', 'stripe', 'paypal', 'credit card'],
    visualIndicators: ['payment form', 'checkout button', 'external payment link'],
  },
  {
    id: 'app_store_5_1_2_subscriptions',
    store: 'app_store',
    category: 'Commerce',
    title: 'Subscription Terms Not Clear',
    description:
      'Apps with auto-renewing subscriptions must clearly display subscription duration, pricing, auto-renewal terms, and cancellation method before purchase.',
    severity: 'high',
    policyReference: 'App Store Review Guidelines 5.1.2',
    keywords: [
      'subscription',
      'auto-renew',
      'recurring',
      'monthly',
      'yearly',
      'cancel',
    ],
    visualIndicators: [
      'subscribe button',
      'premium plan',
      'upgrade screen',
      'pricing tiers',
    ],
  },
  {
    id: 'app_store_3_1_1_data_collection',
    store: 'app_store',
    category: 'Privacy',
    title: 'Data Collection Without Consent',
    description:
      'Apps must request user permission before collecting data. Users must be informed about what data is collected and how it will be used.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 3.1.1',
    keywords: [
      'data collection',
      'tracking',
      'analytics',
      'personal information',
      'permissions',
    ],
    visualIndicators: ['permission dialog', 'tracking request', 'data usage notice'],
  },
  {
    id: 'app_store_5_1_1_hidden_fees',
    store: 'app_store',
    category: 'Commerce',
    title: 'Hidden Costs or Fees',
    description:
      'Apps may not hide costs, require additional purchases to access advertised functionality, or use manipulative tactics to trick users into purchases.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 5.1.1',
    keywords: ['hidden fee', 'surprise charge', 'unexpected cost', 'misleading price'],
    visualIndicators: [
      'unclear pricing',
      'asterisk with hidden terms',
      'bait-and-switch',
    ],
  },
  {
    id: 'app_store_1_1_6_kids_category',
    store: 'app_store',
    category: 'Kids',
    title: 'Kids Category Requirements',
    description:
      'Apps in the Kids Category must not include third-party advertising or analytics, must not link out of the app, and must comply with applicable children\'s privacy laws.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 1.1.6',
    keywords: ['kids', 'children', 'coppa', 'advertising', 'analytics'],
    visualIndicators: ['ad banner', 'external link', 'tracking SDK'],
  },
  {
    id: 'app_store_4_2_6_apple_login',
    store: 'app_store',
    category: 'Authentication',
    title: 'Sign in with Apple Required',
    description:
      'Apps that use third-party or social login services (Facebook, Google, Twitter, etc.) must also offer Sign in with Apple as an equivalent option.',
    severity: 'high',
    policyReference: 'App Store Review Guidelines 4.2.6',
    keywords: [
      'login',
      'sign in',
      'authentication',
      'facebook login',
      'google login',
      'social login',
    ],
    visualIndicators: ['social login buttons', 'authentication screen'],
  },
  {
    id: 'app_store_5_1_1_free_trial_disclosure',
    store: 'app_store',
    category: 'Commerce',
    title: 'Free Trial Terms Missing',
    description:
      'Apps offering free trials must clearly disclose the trial duration, what happens after the trial ends, and how to cancel before being charged.',
    severity: 'high',
    policyReference: 'App Store Review Guidelines 5.1.1',
    keywords: ['free trial', 'trial period', '7-day trial', 'trial ends'],
    visualIndicators: ['start free trial button', 'trial offer screen'],
  },
  {
    id: 'app_store_2_3_10_permissions_purpose',
    store: 'app_store',
    category: 'Privacy',
    title: 'Permission Without Purpose String',
    description:
      'Apps must include purpose strings in their Info.plist for all requested permissions, explaining why the permission is needed.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 2.3.10',
    keywords: [
      'camera permission',
      'location permission',
      'microphone permission',
      'photo library',
      'contacts',
    ],
    visualIndicators: ['system permission dialog', 'permission request screen'],
  },
  {
    id: 'app_store_4_3_design_spam',
    store: 'app_store',
    category: 'Design',
    title: 'Placeholder or Incomplete Content',
    description:
      'Apps must be complete and not contain placeholder content, "lorem ipsum" text, or empty states in production.',
    severity: 'high',
    policyReference: 'App Store Review Guidelines 4.3',
    keywords: ['placeholder', 'lorem ipsum', 'coming soon', 'under construction'],
    visualIndicators: [
      'placeholder text',
      'empty screens',
      'lorem ipsum',
      'test content',
    ],
  },
  {
    id: 'app_store_5_3_gaming',
    store: 'app_store',
    category: 'Gaming',
    title: 'Gambling Content Without Restrictions',
    description:
      'Apps with real-money gambling must be geo-restricted to approved regions and require users to verify age and location.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 5.3',
    keywords: ['gambling', 'casino', 'betting', 'real money', 'poker', 'slots'],
    visualIndicators: ['casino games', 'betting interface', 'deposit money'],
  },
  {
    id: 'app_store_1_4_1_objectionable_content',
    store: 'app_store',
    category: 'Content',
    title: 'Objectionable Content',
    description:
      'Apps with overtly sexual or pornographic material, graphic violence, or defamatory content will be rejected.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 1.4.1',
    keywords: ['explicit content', 'violence', 'pornographic', 'graphic', 'nsfw'],
    visualIndicators: [
      'adult content warning',
      'explicit images',
      'violent imagery',
    ],
  },
  {
    id: 'app_store_2_1_performance_crashes',
    store: 'app_store',
    category: 'Performance',
    title: 'App Crashes or Contains Bugs',
    description:
      'Apps must be stable and not crash frequently. Broken features, obvious bugs, and incomplete implementations will be rejected.',
    severity: 'high',
    policyReference: 'App Store Review Guidelines 2.1',
    keywords: ['crash', 'freeze', 'bug', 'error', 'broken'],
    visualIndicators: ['error message', 'crash dialog', 'frozen screen'],
  },
  {
    id: 'app_store_5_1_4_extensions',
    store: 'app_store',
    category: 'Commerce',
    title: 'Physical Goods or Services Payment',
    description:
      'Apps selling physical goods or services outside the app (e.g., Uber, Airbnb) may use alternative payment methods but not for digital content.',
    severity: 'medium',
    policyReference: 'App Store Review Guidelines 5.1.4',
    keywords: [
      'physical goods',
      'services',
      'ride sharing',
      'food delivery',
      'marketplace',
    ],
    visualIndicators: ['checkout for physical goods', 'service booking'],
  },
  {
    id: 'app_store_3_2_2_unauthorized_data',
    store: 'app_store',
    category: 'Privacy',
    title: 'Unauthorized Data Sharing',
    description:
      'Apps may not share user data with third parties without explicit user consent and disclosure in the privacy policy.',
    severity: 'critical',
    policyReference: 'App Store Review Guidelines 3.2.2',
    keywords: [
      'data sharing',
      'third party',
      'analytics',
      'tracking',
      'privacy policy',
    ],
    visualIndicators: ['privacy consent dialog', 'data sharing notice'],
  },
  {
    id: 'app_store_4_0_design_guidelines',
    store: 'app_store',
    category: 'Design',
    title: 'Poor User Interface Design',
    description:
      'Apps must provide a great user experience. Overly complex, confusing, or poorly designed interfaces may be rejected.',
    severity: 'medium',
    policyReference: 'App Store Review Guidelines 4.0',
    keywords: ['ui', 'ux', 'design', 'interface', 'usability'],
    visualIndicators: ['cluttered screen', 'confusing navigation', 'broken layout'],
  },
  {
    id: 'app_store_2_5_1_sign_in_required',
    store: 'app_store',
    category: 'Authentication',
    title: 'Mandatory Account Creation',
    description:
      'Apps must allow users to browse content without requiring account creation unless account-based features are core to the app.',
    severity: 'medium',
    policyReference: 'App Store Review Guidelines 2.5.1',
    keywords: [
      'forced login',
      'mandatory signup',
      'account required',
      'login wall',
    ],
    visualIndicators: ['login wall', 'forced signup screen'],
  },
];
