import type { ComplianceRule } from './rule-engine';

export const PLAY_STORE_RULES: ComplianceRule[] = [
  {
    id: 'play_store_payments_alternative',
    store: 'play_store',
    category: 'Commerce',
    title: 'Alternative Payment Systems',
    description:
      'Apps distributing or purchasing digital goods must use Google Play Billing unless exempt (e.g., physical goods, peer-to-peer payments).',
    severity: 'critical',
    policyReference: 'Google Play Payment Policy',
    keywords: [
      'payment',
      'billing',
      'purchase',
      'checkout',
      'stripe',
      'paypal',
      'digital goods',
    ],
    visualIndicators: ['payment form', 'checkout screen', 'external payment link'],
  },
  {
    id: 'play_store_subscriptions_disclosure',
    store: 'play_store',
    category: 'Commerce',
    title: 'Subscription Terms Not Disclosed',
    description:
      'Apps with subscriptions must clearly disclose subscription terms, pricing, renewal frequency, trial period details, and cancellation policy.',
    severity: 'high',
    policyReference: 'Google Play Subscription Policy',
    keywords: [
      'subscription',
      'auto-renew',
      'recurring payment',
      'trial',
      'cancel subscription',
    ],
    visualIndicators: [
      'subscription offer',
      'pricing screen',
      'upgrade prompt',
      'trial terms',
    ],
  },
  {
    id: 'play_store_user_data_disclosure',
    store: 'play_store',
    category: 'Privacy',
    title: 'Inadequate Data Disclosure',
    description:
      'Apps must disclose data collection, usage, and sharing practices in the Play Console Data Safety section and provide a privacy policy.',
    severity: 'critical',
    policyReference: 'Google Play User Data Policy',
    keywords: [
      'data collection',
      'privacy policy',
      'data safety',
      'personal information',
      'tracking',
    ],
    visualIndicators: ['data collection notice', 'privacy policy link'],
  },
  {
    id: 'play_store_permissions_sensitive',
    store: 'play_store',
    category: 'Privacy',
    title: 'Sensitive Permissions Without Justification',
    description:
      'Apps requesting sensitive permissions (location, camera, microphone, contacts, etc.) must clearly explain why the permission is needed.',
    severity: 'high',
    policyReference: 'Google Play Permissions Policy',
    keywords: [
      'permissions',
      'location',
      'camera',
      'microphone',
      'contacts',
      'sensitive data',
    ],
    visualIndicators: [
      'permission dialog',
      'permission rationale',
      'access request',
    ],
  },
  {
    id: 'play_store_families_program',
    store: 'play_store',
    category: 'Kids',
    title: 'Families Program Requirements',
    description:
      'Apps targeting children must comply with COPPA, not contain misleading content, and must not include ads that target children based on behavior.',
    severity: 'critical',
    policyReference: 'Google Play Families Policy',
    keywords: [
      'kids',
      'children',
      'family',
      'coppa',
      'child-directed',
      'advertising',
    ],
    visualIndicators: [
      'kid-focused content',
      'child-targeted ads',
      'parental consent',
    ],
  },
  {
    id: 'play_store_misleading_content',
    store: 'play_store',
    category: 'Content',
    title: 'Misleading Claims or Functionality',
    description:
      'Apps must not make false claims about functionality, contain deceptive imagery, or mislead users about app features.',
    severity: 'high',
    policyReference: 'Google Play Misleading Content Policy',
    keywords: [
      'misleading',
      'false claims',
      'deceptive',
      'fake functionality',
      'bait-and-switch',
    ],
    visualIndicators: ['exaggerated claims', 'fake features', 'misleading UI'],
  },
  {
    id: 'play_store_dangerous_content',
    store: 'play_store',
    category: 'Content',
    title: 'Violent or Dangerous Content',
    description:
      'Apps promoting violence, terrorism, self-harm, or other dangerous activities will be rejected.',
    severity: 'critical',
    policyReference: 'Google Play Violent Content Policy',
    keywords: [
      'violence',
      'dangerous',
      'terrorism',
      'self-harm',
      'graphic content',
    ],
    visualIndicators: ['violent imagery', 'graphic content', 'dangerous instructions'],
  },
  {
    id: 'play_store_sexual_content',
    store: 'play_store',
    category: 'Content',
    title: 'Sexual Content or Profanity',
    description:
      'Apps with sexual content, nudity, or profanity must be age-gated and comply with content rating requirements.',
    severity: 'critical',
    policyReference: 'Google Play Sexual Content Policy',
    keywords: [
      'sexual content',
      'nudity',
      'adult content',
      'profanity',
      'explicit',
      'nsfw',
    ],
    visualIndicators: [
      'adult content warning',
      'explicit imagery',
      'sexual themes',
    ],
  },
  {
    id: 'play_store_gambling_real_money',
    store: 'play_store',
    category: 'Gaming',
    title: 'Real-Money Gambling Restrictions',
    description:
      'Apps with real-money gambling must be properly licensed, clearly disclose odds, and restrict access based on user location and age.',
    severity: 'critical',
    policyReference: 'Google Play Gambling Policy',
    keywords: [
      'gambling',
      'real money',
      'casino',
      'betting',
      'poker',
      'slots',
      'lottery',
    ],
    visualIndicators: [
      'casino interface',
      'real-money betting',
      'gambling disclosure',
    ],
  },
  {
    id: 'play_store_spam_low_quality',
    store: 'play_store',
    category: 'Design',
    title: 'Low-Quality or Spam Content',
    description:
      'Apps with placeholder content, "lorem ipsum" text, repetitive content, or minimal functionality will be rejected.',
    severity: 'high',
    policyReference: 'Google Play Spam and Minimum Functionality Policy',
    keywords: [
      'placeholder',
      'lorem ipsum',
      'low quality',
      'spam',
      'minimal functionality',
      'coming soon',
    ],
    visualIndicators: ['placeholder text', 'empty screens', 'test content'],
  },
  {
    id: 'play_store_device_integrity',
    store: 'play_store',
    category: 'Security',
    title: 'Device or Network Abuse',
    description:
      'Apps must not interfere with device functionality, other apps, or network operations. No malware, spyware, or deceptive behavior.',
    severity: 'critical',
    policyReference: 'Google Play Device and Network Abuse Policy',
    keywords: [
      'malware',
      'spyware',
      'device abuse',
      'network interference',
      'security',
    ],
    visualIndicators: ['suspicious permissions', 'background activity warnings'],
  },
  {
    id: 'play_store_intellectual_property',
    store: 'play_store',
    category: 'Content',
    title: 'Intellectual Property Infringement',
    description:
      'Apps must not infringe on trademarks, copyrights, or other intellectual property rights.',
    severity: 'critical',
    policyReference: 'Google Play Intellectual Property Policy',
    keywords: [
      'copyright',
      'trademark',
      'intellectual property',
      'piracy',
      'infringement',
    ],
    visualIndicators: [
      'copyrighted content',
      'trademarked logos',
      'unauthorized branding',
    ],
  },
  {
    id: 'play_store_ads_disruptive',
    store: 'play_store',
    category: 'Advertising',
    title: 'Disruptive or Deceptive Ads',
    description:
      'Ads must not interfere with app functionality, mimic system notifications, or trick users into clicking.',
    severity: 'high',
    policyReference: 'Google Play Ads Policy',
    keywords: [
      'ads',
      'advertising',
      'pop-up',
      'interstitial',
      'deceptive ads',
      'ad placement',
    ],
    visualIndicators: [
      'intrusive ads',
      'misleading ad buttons',
      'fake close buttons',
    ],
  },
  {
    id: 'play_store_ads_children',
    store: 'play_store',
    category: 'Advertising',
    title: 'Ads in Apps for Children',
    description:
      'Apps targeting children must only display ads from Google-certified ad networks and comply with COPPA advertising restrictions.',
    severity: 'critical',
    policyReference: 'Google Play Families Ads Policy',
    keywords: [
      'kids ads',
      'children advertising',
      'coppa ads',
      'family-friendly',
    ],
    visualIndicators: ['ads in kids app', 'child-targeted advertising'],
  },
  {
    id: 'play_store_user_generated_content',
    store: 'play_store',
    category: 'Content',
    title: 'User-Generated Content Without Moderation',
    description:
      'Apps with user-generated content (UGC) must implement content moderation, reporting mechanisms, and comply with harmful content policies.',
    severity: 'high',
    policyReference: 'Google Play User-Generated Content Policy',
    keywords: [
      'ugc',
      'user content',
      'comments',
      'posts',
      'moderation',
      'reporting',
    ],
    visualIndicators: [
      'comment section',
      'user posts',
      'social features',
      'report button',
    ],
  },
  {
    id: 'play_store_target_sdk_version',
    store: 'play_store',
    category: 'Technical',
    title: 'Outdated Target SDK Version',
    description:
      'Apps must target a recent Android API level (currently API 34 or higher for new apps).',
    severity: 'critical',
    policyReference: 'Google Play Target API Level Policy',
    keywords: ['target sdk', 'api level', 'android version', 'outdated sdk'],
    visualIndicators: [],
  },
];
